# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version 
Vagrant.configure("2") do |config|
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/bionic64"


  # Provider-specific configuration
   config.vm.provider "virtualbox" do |vb|
	vb.customize ["modifyvm", :id, "--usb", "on"]
  #   	vb.customize ["modifyvm", :id, "--usbehci", "on"]
  # Connect usb bluetooth here or use UI
  # sudo vboxmanage list usbhost OR lsusb 
  # get VendorID and ProductID and fill in here
	vb.customize ['usbfilter', 'add', '0', 
	       	'--target', :id, 
		'--name', 'btusb', 
		'--vendorid', '0x1131', 
		'--productid', '0x1001']
   end

  config.vm.provision :shell, path: "bootstrap.sh"
end
